kind: Deployment
apiVersion: apps/v1
metadata:
  name: lmarket-ware
  namespace: lmarket
  labels:
    app: lmarket-ware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lmarket-ware
  template:
    metadata:
      labels:
        app: lmarket-ware
    spec:
      containers:
        - name: lmarket-ware
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$PROJECT_NAME:$PROJECT_VERSION
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
kind: Service
apiVersion: v1
metadata:
  name: lmarket-ware
  namespace: lmarket
  labels:
    app: lmarket-ware
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 20032
  selector:
    app: lmarket-ware
  type: NodePort
  clusterIP: None
  sessionAffinity: None
