#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.56.10:3306/lmarket_pms
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#
#  application:
#    name: lmarket-product
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#
server:
  port: 40000
#
#logging:
#  level:
#    com.lmarket: debug
#