spring:

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql-master-service.lmarket:3306/lmarket_pms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: nacos-service.lmarket:8848

    sentinel:
      transport:
        dashboard: sentinel-service.lmarket:1133
        port: 8719

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  thymeleaf:
    cache: false

  application:
    name: lmarket-product

  redis:
    host: redis-service.lmarket
    port: 6379

  session:
    store-type: redis

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      #key-prefix: CACHE_
      use-key-prefix: true
      cache-null-values: true


  zipkin:
    base-url: http://zipkin-service.lmarket:9411/
    discovery-client-enabled: false
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1
    redis:
      enabled: false

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 8080

logging:
  level:
    com.lmarket: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true