spring:
  application:
    name: lmarket-cart

  cloud:
    nacos:
      discovery:
        server-addr: nacos-service.lmarket:8848

    sentinel:
      transport:
        dashboard: sentinel-service.lmarket:1133
        port: 8719

  redis:
    host: redis.lmarket

  thymeleaf:
    cache: false


  zipkin:
    base-url: http://zipkin-service.lmarket:9411/
    discovery-client-enabled: false
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1
    redis:
      enabled: false


server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true