spring:
  application:
    name: lmarket-seckill

  cloud:
    nacos:
      discovery:
        server-addr: nacos-service.lmarket

    sentinel:
      transport:
        dashboard: sentinel-service.lmarket
        port: 8719

  redis:
    host: redis.lmarket
    port: 6379

  rabbitmq:
    host: rabbitmq-management.lmarket
    port: 5672
    virtual-host: /
    listener:
      direct:
        acknowledge-mode: manual

  session:
    store-type: redis

  task:
    execution:
      pool:
        core-size: 20
        max-size: 50

  thymeleaf:
    cache: false


  zipkin:
    base-url: http://zipkin-service.lmarket
    discovery-client-enabled: false
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1
    redis:
      enabled: false



server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true