spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql-master-service.lmarket:3306/lmarket_oms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: nacos-service.lmarket:8848

    sentinel:
      transport:
        dashboard: sentinel-service.lmarket:1133
        port: 8719

  application:
    name: lmarket-order

  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

  thymeleaf:
    cache: false

  rabbitmq:
    host: rabbitmq-managent-service.lmarket
    port: 5672
    virtual-host: /

      # 手动ack消息 消息不容易丢失
    listener:
      simple:
        acknowledge-mode: manual

  redis:
    host: redis-service.lmarket
    port: 6379

  session:
    store-type: redis

  zipkin:
    base-url: http://zipkin-service.lmarket:9411/
    discovery-client-enabled: false
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1
    redis:
      enabled: false

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true