spring:
  application:
    name: lmarket-third-party
  cloud:
    nacos:
      discovery:
        server-addr: nacos-service.lmarket
    alicloud:
      access-key: LTAI4GFmAuvbsrEwYpBHNdHb
      secret-key: SAMZVZhAAuv7gqYSgEWKccDe6CAXGh
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com

      sms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        template: 908e94ccf08b4476ba6c876d13f084ad
        smsSign: 2e65b1bb3d054466b82f0c9d125465e2
        appcode: ef4552bd33044284bd7f5e550a5a515b

  zipkin:
    base-url: http://zipkin-service.lmarket
    discovery-client-enabled: false
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1
    redis:
      enabled: false



server:
  port: 8080