spring:

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql-master.lmarket/lmarket_sms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: nacos-service.lmarket

    sentinel:
      transport:
        dashboard: sentinel-service.lmarket
        port: 8719

  application:
    name: lmarket-coupon


  zipkin:
    base-url: http://zipkin-service.lmarket
    discovery-client-enabled: false
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1
    redis:
      enabled: false

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true